# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: '^source/engine/user-engine/.*$'
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-format
  - id: cpplint
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.28.0
  hooks:
  - id: yamllint
    args: [-c=/path/to/.yamllint]
- repo: local
  hooks:
  - id: gen-docs
    name: gen-docs
    entry: source/engine/user-engine/tests/generate-docs
    language: script
    pass_filenames: false
  - id: run-coverage
    name: run-coverage
    entry: source/engine/user-engine/tests/run-coverage
    language: script
    pass_filenames: false
  - id: run-clang-tidy
    name: run-clang-tidy
    entry: source/engine/user-engine/tests/run-clang-tidy
    language: script
    pass_filenames: false
