# for Android environment
name: NDK CI (for Android)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        edition:
          - USER_ENGINE

    steps:
      # https://developer.android.com/ndk/downloads?hl=ja#stable-downloads
      - name: Setup Android NDK r26b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      - name: Checkout own repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: ndk-build
        run: ./main/script/android_build.sh -e ${{ matrix.edition }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-android_${{ github.run_number }}_${{ github.sha }}
          path: ./main/build/**/*
